import uuid
from abc import ABC, abstractmethod
from typing import List, Optional

from app.domain.models import Category, Item, ListType, Store, StoreType, User


class IUserRepository(ABC):
    @abstractmethod
    def get_all(self) -> List[User]: ...
    @abstractmethod
    def get_by_id(self, user_id: uuid.UUID) -> Optional[User]: ...
    @abstractmethod
    def get_by_name(self, name: str) -> Optional[User]: ...
    @abstractmethod
    def create(self, name: str, alias: Optional[str] = None) -> User: ...
    @abstractmethod
    def update_alias(self, user_id: uuid.UUID, alias: str) -> Optional[User]: ...
    @abstractmethod
    def delete(self, user_id: uuid.UUID) -> None: ...


class ICategoryRepository(ABC):
    @abstractmethod
    def get_all(self) -> List[Category]: ...
    @abstractmethod
    def get_by_id(self, category_id: uuid.UUID) -> Optional[Category]: ...
    @abstractmethod
    def create(self, name: str) -> Category: ...
    @abstractmethod
    def update(self, category_id: uuid.UUID, name: str) -> Category: ...
    @abstractmethod
    def delete(self, category_id: uuid.UUID) -> None: ...


class IStoreRepository(ABC):
    @abstractmethod
    def get_all(self, store_type: Optional[StoreType] = None) -> List[Store]: ...
    @abstractmethod
    def get_by_id(self, store_id: uuid.UUID) -> Optional[Store]: ...
    @abstractmethod
    def create(self, name: str, store_type: StoreType = StoreType.MERCADO) -> Store: ...
    @abstractmethod
    def update(self, store_id: uuid.UUID, name: str, store_type: Optional[StoreType] = None) -> Optional[Store]: ...
    @abstractmethod
    def delete(self, store_id: uuid.UUID) -> None: ...


class IItemRepository(ABC):
    @abstractmethod
    def get_all(self, list_type: Optional[ListType] = None, category_id: Optional[uuid.UUID] = None, store_id: Optional[uuid.UUID] = None, user_id: Optional[uuid.UUID] = None, checked: Optional[bool] = None) -> List[Item]: ...
    @abstractmethod
    def get_by_id(self, item_id: uuid.UUID) -> Optional[Item]: ...
    @abstractmethod
    def create(self, item: Item) -> Item: ...
    @abstractmethod
    def update(self, item_id: uuid.UUID, data: dict) -> Item: ...
    @abstractmethod
    def delete(self, item_id: uuid.UUID) -> None: ...
    @abstractmethod
    def toggle_checked(self, item_id: uuid.UUID) -> Item: ...
